### ISSUE TITLE
Error processing 'after'

### ISSUE THREAD

**Issue by jurajseffer** [getsentry/sentry-slack#14]
Running Sentry 7.1.4 with 0.1.0 sentry-slack. The "Test Configuration" button works OK and creates a notification on Slack but actual logged exception does not, this is from the sentry log on the server:

```
[ERROR] Error processing 'after' on 'NotifyEventServiceAction': u'slack'
Traceback (most recent call last):
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/rules/actions/notify_event_service.py", line 44, in after
    plugin = plugins.get(service)
  File "/www/sentry/local/lib/python2.7/site-packages/sentry/plugins/base/manager.py", line 49, in get
    raise KeyError(slug)
KeyError: u'slack'
```

**Comment by dcramer** [comment]
Did you restart your workers after you installed sentry-slack? This is saying the plugin isnt registered.
