### ISSUE TITLE
Error sending notify

### ISSUE THREAD

**Issue by paulomcnally** [getsentry/sentry-slack#16]
2015-05-19T21:37:54.292599+00:00 app[web.1]: Error processing 'post_process' on 'SlackPlugin': __init__() got an unexpected keyword argument '_context'
    2015-05-19T21:37:54.292604+00:00 app[web.1]: Traceback (most recent call last):
    2015-05-19T21:37:54.292622+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/utils/safe.py", line 19, in safe_execute
    2015-05-19T21:37:54.292623+00:00 app[web.1]:     result = func(*args, **kwargs)
    2015-05-19T21:37:54.292625+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 110, in post_process
    2015-05-19T21:37:54.292626+00:00 app[web.1]:     self.notify_users(group, event)
    2015-05-19T21:37:54.292628+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry_slack/plugin.py", line 95, in notify_users
    2015-05-19T21:37:54.292629+00:00 app[web.1]:     return urllib2.urlopen(request).read()
    2015-05-19T21:37:54.292631+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib2.py", line 154, in urlopen
    2015-05-19T21:37:54.292632+00:00 app[web.1]:     return opener.open(url, data, timeout)
    2015-05-19T21:37:54.292634+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib2.py", line 431, in open
    2015-05-19T21:37:54.292635+00:00 app[web.1]:     response = self._open(req, data)
    2015-05-19T21:37:54.292636+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib2.py", line 449, in _open
    2015-05-19T21:37:54.292638+00:00 app[web.1]:     '_open', req)
    2015-05-19T21:37:54.292639+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib2.py", line 409, in _call_chain
    2015-05-19T21:37:54.292641+00:00 app[web.1]:     result = func(*args)
    2015-05-19T21:37:54.292642+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib2.py", line 1240, in https_open
    2015-05-19T21:37:54.292643+00:00 app[web.1]:     context=self._context)
    2015-05-19T21:37:54.292645+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/urllib2.py", line 1194, in do_open
    2015-05-19T21:37:54.292646+00:00 app[web.1]:     h.request(req.get_method(), req.get_selector(), req.data, headers)
    2015-05-19T21:37:54.292647+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 1001, in request
    2015-05-19T21:37:54.292649+00:00 app[web.1]:     self._send_request(method, url, body, headers)
    2015-05-19T21:37:54.292651+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 1035, in _send_request
    2015-05-19T21:37:54.292653+00:00 app[web.1]:     self.endheaders(body)
    2015-05-19T21:37:54.292654+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 997, in endheaders
    2015-05-19T21:37:54.292655+00:00 app[web.1]:     self._send_output(message_body)
    2015-05-19T21:37:54.292657+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 850, in _send_output
    2015-05-19T21:37:54.292658+00:00 app[web.1]:     self.send(msg)
    2015-05-19T21:37:54.292659+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 812, in send
    2015-05-19T21:37:54.292660+00:00 app[web.1]:     self.connect()
    2015-05-19T21:37:54.292662+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/httplib.py", line 1212, in connect
    2015-05-19T21:37:54.292663+00:00 app[web.1]:     server_hostname=server_hostname)
    2015-05-19T21:37:54.292664+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/ssl.py", line 350, in wrap_socket
    2015-05-19T21:37:54.292665+00:00 app[web.1]:     _context=self)
    2015-05-19T21:37:54.292667+00:00 app[web.1]: TypeError: __init__() got an unexpected keyword argument '_context'

**Comment by mattrobenolt** [comment]
Not sure what the issue here is, but it's down inside the `urllib2` call in the ssl library trying to wrap the socket for ssl.

It's highly unlikely that this is an issue with `sentry-slack` since we do nothing to affect that. I'd start by making sure a urllib2 call to any https url works in your heroku environment.
