### ISSUE TITLE
AttributeError in self.get_option('username', project).strip()  [Sentry 8.0.1]

### ISSUE THREAD

**Issue by rev112** [getsentry/sentry-slack#31]
After upgrading to Sentry 8.0.1 and sentry-slack 0.4.0 I get the following error while testing the Slack integration:

```
[ERROR] Plugin(slack) raised an error during test                                                  
Traceback (most recent call last):                                                                 
  File "/home/beta/sentry_env/local/lib/python2.7/site-packages/sentry/plugins/base/configuration.py", line 41, in default_plugin_config                                                              
    test_results = plugin.test_configuration(project)                                              
  File "/home/beta/sentry_env/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 156, in test_configuration                                                                      
    return self.notify(notification)                                                               
  File "/home/beta/sentry_env/local/lib/python2.7/site-packages/sentry/../sentry_slack/plugin.py",  line 129, in notify                                                                                
    username = self.get_option('username', project).strip()                                        
AttributeError: 'NoneType' object has no attribute 'strip'                                         
```
Looks like it's related to #29, patching `username` and `channel` (same error) worked as a temporary fix.

**Comment by mattrobenolt** [comment]
This was fixed for 0.5.0.
