### ISSUE TITLE
Can't find slack integration after update.

### ISSUE THREAD

**Issue by omss24** [getsentry/sentry-slack#33]
I just updated from version 7.7.4 to 8.0.3 of sentry. I can see the sentry-slack in packages and installed_apps, but in my intregation list i cant see the sentry-slack section.

**Comment by mattrobenolt** [comment]
Can you provide some more information?

If there was an issue, there'd be some stack trace when the server booted up.

**Comment by omss24** [comment]
I only got this, but I dont this is related.

```python
2016-01-23T00:25:45.730533+00:00 app[web.1]: Failed to load plugin 'github':
2016-01-23T00:25:45.730549+00:00 app[web.1]: Traceback (most recent call last):
2016-01-23T00:25:45.730551+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/runner/initializer.py", line 38, in register_plugins
2016-01-23T00:25:45.730552+00:00 app[web.1]:     plugin = ep.load()
2016-01-23T00:25:45.730553+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2379, in load
2016-01-23T00:25:45.730553+00:00 app[web.1]:     self.require(*args, **kwargs)
2016-01-23T00:25:45.730554+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2396, in require
2016-01-23T00:25:45.730554+00:00 app[web.1]:     items = working_set.resolve(reqs, env, installer)
2016-01-23T00:25:45.730555+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
2016-01-23T00:25:45.730556+00:00 app[web.1]:     raise VersionConflict(dist, req).with_context(dependent_req)
2016-01-23T00:25:45.730559+00:00 app[web.1]: ContextualVersionConflict: (psycopg2 2.6 (/app/.heroku/python/lib/python2.7/site-packages), Requirement.parse('psycopg2<2.6.0,>=2.5.0'), set(['sentry']))
2016-01-23T00:25:45.730559+00:00 app[web.1]: 
2016-01-23T00:25:45.735895+00:00 app[web.1]: Failed to load plugin 'slack':
2016-01-23T00:25:45.735901+00:00 app[web.1]: Traceback (most recent call last):
2016-01-23T00:25:45.735903+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sentry/runner/initializer.py", line 38, in register_plugins
2016-01-23T00:25:45.735904+00:00 app[web.1]:     plugin = ep.load()
2016-01-23T00:25:45.735904+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2379, in load
2016-01-23T00:25:45.735905+00:00 app[web.1]:     self.require(*args, **kwargs)
2016-01-23T00:25:45.735906+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2396, in require
2016-01-23T00:25:45.735906+00:00 app[web.1]:     items = working_set.resolve(reqs, env, installer)
2016-01-23T00:25:45.735907+00:00 app[web.1]:   File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 854, in resolve
2016-01-23T00:25:45.735908+00:00 app[web.1]:     raise VersionConflict(dist, req).with_context(dependent_req)
2016-01-23T00:25:45.735909+00:00 app[web.1]: ContextualVersionConflict: (psycopg2 2.6 (/app/.heroku/python/lib/python2.7/site-packages), Requirement.parse('psycopg2<2.6.0,>=2.5.0'), set(['sentry']))
```

**Comment by omss24** [comment]
I was psycopg2 version, changed to: psycopg2 == 2.5.0
