### ISSUE TITLE
Unable to install slack plugin with sentry 8.5.0

### ISSUE THREAD

**Issue by Stefan2505** [getsentry/sentry-slack#47]
Hi,
i tried to install slack plugin with the latest sentry version 8.5.0 but it didn't work.

Any idea?

**Comment by mattrobenolt** [comment]
Can you clarify "it didn't work?"

**Comment by jeroennijhof** [comment]
```
sentry-cron Failed to load plugin 'slack':
sentry-cron Traceback (most recent call last):
sentry-cron   File "/usr/share/nginx/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 42, in register_plugins
sentry-cron     plugin = ep.load()
sentry-cron   File "/usr/share/nginx/sentry/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2228, in load
sentry-cron     self.require(*args, **kwargs)
sentry-cron   File "/usr/share/nginx/sentry/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2245, in require
sentry-cron     items = working_set.resolve(reqs, env, installer)
sentry-cron   File "/usr/share/nginx/sentry/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
sentry-cron     raise VersionConflict(dist, req).with_context(dependent_req)
sentry-cron ContextualVersionConflict: (requests 2.10.0 (/usr/share/nginx/sentry/lib/python2.7/site-packages), Requirement.parse('requests[security]<2.10.0,>=2.9.1'), set(['sentry']))
```

**Comment by jeroennijhof** [comment]
I manage the solve it by installing requests version 2.9.2 and msg-pack.
