### ISSUE TITLE
Error when running test

### ISSUE THREAD

**Issue by brianwu02** [getsentry/sentry-slack#59]
Hey all, using the standalone sentry server. Just installed sentry-slack, configured it and am getting this exception when running the test:

```Traceback (most recent call last):
  File "/home/deploy/sentry/local/lib/python2.7/site-packages/sentry/api/endpoints/project_plugin_details.py", line 55, in post
    test_results = plugin.test_configuration(project)
  File "/home/deploy/sentry/local/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 160, in test_configuration
    return self.notify(notification)
  File "/home/deploy/sentry/local/lib/python2.7/site-packages/sentry_plugins/slack/plugin.py", line 238, in notify
    'title_link': self.add_notification_referrer_param(group.get_absolute_url()),
AttributeError: 'SlackPlugin' object has no attribute 'add_notification_referrer_param'
18:04:57 [ERROR] root: Plugin(slack) raised an error during test```

any guidance is appreciated, thank you!

**Comment by mattrobenolt** [comment]
This repository is no longer maintained and is no longer recommended. See https://github.com/getsentry/sentry-plugins instead.
